### get
GET http://localhost:8080/

### new
POST http://localhost:8080/create
Content-Type: application/json

{
  "wer": "mert"
}

### save
PUT http://localhost:8080/update

### update
PUT http://localhost:8080/update
Content-Type: application/json

{
  "wer":"mert",
  "was":"apfel",
  "wo":"lidl",
  "wann":"2023-12-13"
}